
export enum PaymentStatus {
    NOT_INITIATED = 'NOT_INITIATED',
    NOT_INITIATED_INSUFFICIENT_FUNDS = 'NOT_INITIATED_INSUFFICIENT_FUNDS',
    NOT_INITIATED_DISCONNECTED_ACCOUNT = 'NOT_INITIATED_DISCONNECTED_ACCOUNT',
    INITIATED_PRE_FLIGHT = 'INITIATED_PRE_FLIGHT',
    INITIATED = 'INITIATED',
    PROCESSED = 'PROCESSED',
    FAILED_ATTEMPT = 'FAILED_ATTEMPT',
    FAILED_SYSTEM = 'FAILED_SYSTEM',
}
